# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_user_admin'),
        ('harttv_app', '0005_episode_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='favorite',
        ),
        migrations.AddField(
            model_name='show',
            name='favorite',
            field=models.ManyToManyField(related_name='users_favorites', to='login_registration.User'),
        ),
    ]
