# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_user_admin'),
        ('harttv_app', '0006_auto_20170627_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='watched',
            field=models.ManyToManyField(related_name='watched_episodes', to='login_registration.User'),
        ),
    ]
