# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harttv_app', '0009_showrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
