# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harttv_app', '0010_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='harttv_app.ShowRating'),
            preserve_default=False,
        ),
    ]
