# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0003_remove_user_birthday'),
        ('harttv_app', '0011_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_show', to='harttv_app.Show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_user', to='login_registration.User')),
            ],
        ),
    ]
